// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXMn615ffuOs9ex0AQtdXy5-mhpsSiobQ',
    appId: '1:436744911101:web:a4a9805e7a332d352b2694',
    messagingSenderId: '436744911101',
    projectId: 'chatting-4850c',
    authDomain: 'chatting-4850c.firebaseapp.com',
    storageBucket: 'chatting-4850c.appspot.com',
    measurementId: 'G-K4NTDN5JG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqV7Qq0C_a059tfSDUAPGfn_d1GHwysIs',
    appId: '1:436744911101:android:afe3118b1cf76d1d2b2694',
    messagingSenderId: '436744911101',
    projectId: 'chatting-4850c',
    storageBucket: 'chatting-4850c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUQvpZpDzrN2j9p3kg_Lu9zE1ytgPAuH0',
    appId: '1:436744911101:ios:7ba36753165d5fc82b2694',
    messagingSenderId: '436744911101',
    projectId: 'chatting-4850c',
    storageBucket: 'chatting-4850c.appspot.com',
    iosBundleId: 'com.example.chatingApp',
  );
}
